import * as dotenv from 'dotenv'
dotenv.config()

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const items = [
  {
    title: '发改委：2026年起再生塑料企业享受增值税即征即退50%优惠',
    titleZh: '发改委：2026年起再生塑料企业享受增值税即征即退50%优惠',
    titleEn: 'NDRC: Plastic Recyclers to Receive 50% VAT Rebate from 2026',
    summary: '国家发展改革委发布通知，自2026年1月1日起，符合条件的再生塑料加工企业可享受增值税即征即退50%的优惠政策，预计惠及全国3,200余家规模以上企业。',
    summaryZh: '国家发展改革委发布通知，自2026年1月1日起，符合条件的再生塑料加工企业可享受增值税即征即退50%的优惠政策，预计惠及全国3,200余家规模以上企业。',
    summaryEn: 'China\'s NDRC has announced that qualified plastic recycling processors will receive a 50% VAT rebate starting January 2026, benefiting an estimated 3,200+ above-scale enterprises nationwide.',
    category: 'policy',
    pillars: 'recycling,materials',
    countryCode: 'CN',
    importance: 5,
    isHot: true,
    isPremium: false,
    source: '国家发展改革委',
    sourceUrl: 'https://www.ndrc.gov.cn',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-26'),
  },
  {
    title: 'PPWR正式生效：欧盟要求2030年PET饮料瓶含30% PCR',
    titleZh: 'PPWR正式生效：欧盟要求2030年PET饮料瓶含30% PCR',
    titleEn: 'PPWR Takes Effect: EU Mandates 30% PCR in PET Bottles by 2030',
    summary: '欧盟《包装和包装废弃物法规》（PPWR）关键条款正式生效，要求PET饮料瓶在2030年前须含至少30%消费后再生料（PCR），违规企业将面临最高年营业额4%的罚款。',
    summaryZh: '欧盟《包装和包装废弃物法规》（PPWR）关键条款正式生效，要求PET饮料瓶在2030年前须含至少30%消费后再生料（PCR），违规企业将面临最高年营业额4%的罚款。',
    summaryEn: 'Key clauses of the EU Packaging and Packaging Waste Regulation (PPWR) have entered into force, requiring PET beverage bottles to contain at least 30% PCR by 2030. Non-compliance may incur fines of up to 4% of annual turnover.',
    category: 'policy',
    pillars: 'recycling,reuse',
    countryCode: 'EU',
    importance: 5,
    isHot: true,
    isPremium: false,
    source: 'Plastics Recyclers Europe',
    sourceUrl: 'https://www.plasticsrecyclers.eu',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-25'),
  },
  {
    title: '华南rPET瓶片价格本周回调200元/吨，供给端压力有所释放',
    titleZh: '华南rPET瓶片价格本周回调200元/吨，供给端压力有所释放',
    titleEn: 'South China rPET Bottle Flake Prices Drop CNY 200/t This Week',
    summary: '卓创资讯数据显示，华南地区rPET瓶片本周均价跌至6,800元/吨，较上周下调200元。分析师指出，近期进口废瓶到港量增加叠加下游纺丝需求疲软，共同推动价格回调。',
    summaryZh: '卓创资讯数据显示，华南地区rPET瓶片本周均价跌至6,800元/吨，较上周下调200元。分析师指出，近期进口废瓶到港量增加叠加下游纺丝需求疲软，共同推动价格回调。',
    summaryEn: 'According to SCI99 data, South China rPET bottle flake average prices fell to CNY 6,800/t this week, down CNY 200 from last week. Analysts cite rising import volumes and weak downstream fiber demand as key drivers.',
    category: 'market',
    pillars: 'recycling,materials',
    countryCode: 'CN',
    importance: 4,
    isHot: true,
    isPremium: false,
    source: '卓创资讯',
    sourceUrl: 'https://plastic.sci99.com',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-26'),
  },
  {
    title: 'APR发布2025年塑料回收设计指南更新版，新增柔性包装规范',
    titleZh: 'APR发布2025年塑料回收设计指南更新版，新增柔性包装规范',
    titleEn: 'APR Releases Updated 2025 Design Guide for Plastics Recyclability',
    summary: 'APR（美国塑料回收协会）发布2025版《可回收性设计指南》，首次纳入柔性包装专项规范，明确界定聚乙烯薄膜袋回收兼容性测试标准，并更新了多层复合材料的分离要求。',
    summaryZh: 'APR（美国塑料回收协会）发布2025版《可回收性设计指南》，首次纳入柔性包装专项规范，明确界定聚乙烯薄膜袋回收兼容性测试标准，并更新了多层复合材料的分离要求。',
    summaryEn: 'The Association of Plastic Recyclers (APR) has released its 2025 Design Guide for Plastics Recyclability, for the first time incorporating flexible packaging specifications, defining PE film bag compatibility test standards and updating multi-layer separation requirements.',
    category: 'tech',
    pillars: 'recycling,auxiliaries',
    countryCode: 'US',
    importance: 4,
    isHot: false,
    isPremium: false,
    source: 'APR',
    sourceUrl: 'https://www.plasticsrecycling.org',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-24'),
  },
  {
    title: '注塑机节能改造补贴政策落地，单台最高补贴15万元',
    titleZh: '注塑机节能改造补贴政策落地，单台最高补贴15万元',
    titleEn: 'China Subsidy Policy for Injection Molding Machine Upgrades: Up to CNY 150k Per Unit',
    summary: '工信部联合财政部发布注塑设备节能改造补贴细则，采用伺服驱动改造的旧式液压注塑机可获单台最高15万元补贴，全电动注塑机新购最高补贴20万元，政策有效期至2027年底。',
    summaryZh: '工信部联合财政部发布注塑设备节能改造补贴细则，采用伺服驱动改造的旧式液压注塑机可获单台最高15万元补贴，全电动注塑机新购最高补贴20万元，政策有效期至2027年底。',
    summaryEn: 'China\'s MIIT and MOF have issued subsidy details for injection molding energy upgrades. Servo-drive retrofits on hydraulic machines qualify for up to CNY 150k/unit; new all-electric machines up to CNY 200k/unit. Policy valid through end-2027.',
    category: 'policy',
    pillars: 'molding',
    countryCode: 'CN',
    importance: 4,
    isHot: false,
    isPremium: false,
    source: '工业和信息化部',
    sourceUrl: 'https://www.miit.gov.cn',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-23'),
  },
  {
    title: 'Sabic推出全球首款食品接触级化学回收PP再生料',
    titleZh: 'Sabic推出全球首款食品接触级化学回收PP再生料',
    titleEn: 'Sabic Launches World\'s First Food-Contact Grade Chemically Recycled rPP',
    summary: 'Sabic宣布旗下LNP™系列推出全球首款通过欧盟食品接触认证的化学回收聚丙烯（rPP），采用热解油为原料，可实现闭环食品包装应用，为PP化学回收商业化树立里程碑。',
    summaryZh: 'Sabic宣布旗下LNP™系列推出全球首款通过欧盟食品接触认证的化学回收聚丙烯（rPP），采用热解油为原料，可实现闭环食品包装应用，为PP化学回收商业化树立里程碑。',
    summaryEn: 'Sabic has announced a food-contact certified chemically recycled PP (rPP) under its LNP™ series — the world\'s first. Produced from pyrolysis oil feedstock, it enables closed-loop food packaging applications and marks a milestone for commercial-scale chemical recycling of PP.',
    category: 'tech',
    pillars: 'materials,recycling',
    countryCode: 'GLOBAL',
    importance: 5,
    isHot: true,
    isPremium: true,
    source: 'Sustainable Plastics',
    sourceUrl: 'https://www.sustainableplastics.com',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-22'),
  },
  {
    title: '生物基增塑剂替代传统DEHP，欧洲市场需求年增35%',
    titleZh: '生物基增塑剂替代传统DEHP，欧洲市场需求年增35%',
    titleEn: 'Bio-Based Plasticizers Displace DEHP: European Demand Growing 35% YoY',
    summary: 'ICIS最新报告显示，受欧盟SVHCs限制法规驱动，欧洲生物基增塑剂市场2025年同比增长35%，柠檬酸酯类和环氧大豆油衍生物成为替代DEHP的主流选择，主要应用于医疗器械和食品包装领域。',
    summaryZh: 'ICIS最新报告显示，受欧盟SVHCs限制法规驱动，欧洲生物基增塑剂市场2025年同比增长35%，柠檬酸酯类和环氧大豆油衍生物成为替代DEHP的主流选择，主要应用于医疗器械和食品包装领域。',
    summaryEn: 'Per ICIS, driven by EU SVHC restrictions, Europe\'s bio-based plasticizer market grew 35% YoY in 2025. Citrate esters and epoxidized soybean oil derivatives are the leading DEHP alternatives, primarily in medical devices and food packaging.',
    category: 'market',
    pillars: 'additives',
    countryCode: 'EU',
    importance: 3,
    isHot: false,
    isPremium: false,
    source: 'ICIS',
    sourceUrl: 'https://www.icis.com',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-21'),
  },
  {
    title: '热流道模具数字化监控系统市场规模2025年达42亿元',
    titleZh: '热流道模具数字化监控系统市场规模2025年达42亿元',
    titleEn: 'Hot Runner Mold Digital Monitoring Market Reaches CNY 4.2B in 2025',
    summary: '中国模具工业协会发布年度报告，2025年国内热流道模具配套数字化监控系统市场规模达42亿元，同比增长28%，实时压力/温度传感器和AI异常预警成为主要增长驱动。',
    summaryZh: '中国模具工业协会发布年度报告，2025年国内热流道模具配套数字化监控系统市场规模达42亿元，同比增长28%，实时压力/温度传感器和AI异常预警成为主要增长驱动。',
    summaryEn: 'The China Mold Industry Association annual report shows the domestic hot runner mold digital monitoring market reached CNY 4.2B in 2025, up 28% YoY. Real-time pressure/temperature sensors and AI anomaly detection are the primary growth drivers.',
    category: 'market',
    pillars: 'molds',
    countryCode: 'CN',
    importance: 3,
    isHot: false,
    isPremium: false,
    source: '中国模具工业协会',
    sourceUrl: 'https://www.cdmia.com.cn',
    translateStatus: 'translated',
    publishedAt: new Date('2026-04-20'),
  },
]

async function main() {
  console.log('Seeding intelligence data...')
  for (const item of items) {
    await prisma.intelligence.create({ data: item })
    console.log(`✓ ${item.title.slice(0, 30)}...`)
  }
  console.log(`\nDone! Inserted ${items.length} intelligence items.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
